# write a program to input 2 number and print their sum
opera1=int(input("Enter First Number:"))
opera2=int(input("Enter second number:"))
sum=opera1+opera2
print("Solution is",sum)



#area of square

opera1=int(input("Enter size of side:"))
sum=opera1**2
print("Solution is:",sum)


#average of 2 f;oting number

opera1=float(input("Enter first floting number:"))
opera2=float(input("Enter second floting number:"))
avg=(opera2+opera1)/2
print(avg)